[project]
name = "ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "granian>=2.3.1",
    "numpy>=2.2.6",
    "opencv-python-headless>=4.11.0.86",
    "python-doctr[torch]>=0.11.0",    
    "torch>=2.7.0",
    "torchvision>=0.22.0",
]

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[dependency-groups]
dev = [
    "clearml>=2.0.0",
    "matplotlib>=3.10.3",
    "onnxtr[gpu-headless]>=0.6.3",
    "slack-sdk>=3.35.0",
    "wandb>=0.19.11",
]
